thecool={ [true]=-0.7, [false]=0.7 }
thecool2={ [true]=180, [false]=0 }
lastConductorPos = 0
function onSongStart()
ogposx0 = getPropertyFromGroup('opponentStrums', 0, 'x')
ogposy0 = getPropertyFromGroup('opponentStrums', 0, 'y');
ogposx1 = getPropertyFromGroup('opponentStrums', 1, 'x')
ogposy1 = getPropertyFromGroup('opponentStrums', 1, 'y');
	ogposx2 = getPropertyFromGroup('opponentStrums', 2, 'x');
	ogposy2 = getPropertyFromGroup('opponentStrums', 2, 'y');
	ogposx3 = getPropertyFromGroup('opponentStrums', 3, 'x');
	ogposy3 = getPropertyFromGroup('opponentStrums', 3, 'y');
	ogposx4 = getPropertyFromGroup('playerStrums', 0, 'x');
	ogposy4 = getPropertyFromGroup('playerStrums', 0, 'y');
	ogposx5 = getPropertyFromGroup('playerStrums', 1, 'x');
	ogposy5 = getPropertyFromGroup('playerStrums', 1, 'y');
	ogposx6 = getPropertyFromGroup('playerStrums', 2, 'x');
	ogposy6 = getPropertyFromGroup('playerStrums', 2, 'y');
	ogposx7 = getPropertyFromGroup('playerStrums', 3, 'x');
	ogposy7 = getPropertyFromGroup('playerStrums', 3, 'y');
end
function onUpdate(elapsed)

	ballssimulatorroblox = getSongPosition();
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls04', 0, (0 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls44', 4, (0 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls14', 1, (90 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls54', 5, (90 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls24', 2, (-90 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls64', 6, (-90 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls34', 3, (180 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
notetime = 500 * 0.5
if notetime <= ballssimulatorroblox + 3 then
if notetime >= lastconductorpos then
noteTweenDirection('balls74', 7, (180 * (thecool[downscroll]) / 0.7) + thecool2[downscroll], 0.5, 'sineInOut')
end
end
lastconductorpos = ballssimulatorroblox
end
--generated by methewhenmethes modchart editor